apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args: ["npm run db:migrate && npm run db:fixtures"]
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.postgres }}
                key: database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.postgres }}
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.postgres }}
                key: password
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.postgres }}
                key: host
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.redis }}
                key: host
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.redis }}
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.redis }}
                key: password
      restartPolicy: Never